Add triggers firing on less items than all
MCLD/gra4 pull request #213
Opened 2017-03-06 17:54 UTC by iafb

- Add #175 Allow triggers to fire on less items than all

2017-03-06 22:21 UTC, k7hpn reviewed
Just to make sure I understand how this works...

2017-03-06 22:21 UTC, haraldnagel commented on src/GRA.Data/Repository/TriggerRepository.cs
> +            var itemTriggers = triggers.Where(_ => _.ItemsRequired > 0);
So this means that in order for badges and challenges to work from here on forward the `ItemsRequired` property will need to be set, am I reading that right?

2017-03-06 22:25 UTC, iafb commented on src/GRA.Data/Repository/TriggerRepository.cs
> +            var itemTriggers = triggers.Where(_ => _.ItemsRequired > 0);
The `ItemsRequired` field is a non-nullable int so it gets set to default if the user doesn't enter anything for it.

2017-03-07 00:22 UTC, k7hpn requested changes
I opened a PR where I made the required challenges/triggers into a panel, I think we should use the disclosure-triangle approach we use at the bottom for awards on the require challenges/triggers. What do you think?

I also added a "No challenges/triggers required" row when there are none but your magic adding stuff doesn't remove that row, can you modify your logic to handle that properly?

2017-03-07 19:49 UTC, merged